### PR TITLE
Added Functionality to the Anchor Tag

### PR DESCRIPTION
**Pull request by Srijan-Baniyal**
When someone will click the button, it'll open a new tab in the browser.

### CODE REVIEW

**Comment by Srijan-Baniyal** [comment]
@pawarspeaks  . I just wanted to ask that when will this Pr will  get merged??

**Comment by pawarspeaks** [comment]
@Srijan-Baniyal hey thanks for noticing and making this change, could you please add some online/offline event and then resend this pr as an updated with both the changes?

**Comment by Srijan-Baniyal** [comment]
Umm like the vercel event and github universe??

**Comment by Srijan-Baniyal** [comment]
> @Srijan-Baniyal hey thanks for noticing and making this change, could you please add some online/offline event and then resend this pr as an updated with both the changes?

Yeah sure

**Comment by Srijan-Baniyal** [comment]
hey @pawarspeaks  I have added the Vercel Event You were saying to add. You can see it in the online events section .

**Comment by Srijan-Baniyal** [comment]
Can I do More PR for HacktoberFest ??? After this ???

**Comment by pawarspeaks** [comment]
@Srijan-Baniyal we've merged this, also added the Hacktoberfest label!
yes you can still contribute to this project for hacktoberfest!
Do ⭐ the repo!

**Pull request merged**
