### PR TITLE
Contact us Page optimised

### PR DESCRIPTION
**Pull request by bhaveshgarg2000**
Contact Us page Optimised 
Thanks for giving me this Opportunity...

### CODE REVIEW

**Comment by pawarspeaks** [comment]
Hey @bhaveshgarg2000 the changes you made aren't in a good functioning at the moment, I would suggest to replace the socials  where they were intially or either get the mail id aligned to the center.Also for the form submission button its not working in your neither i could see any submission confirmation, I suggest you to make some functional changes. Happy Open sourcing! see you around!

**Comment by pawarspeaks** [comment]
@bhaveshgarg2000 are you still working on it?

**Comment by bhaveshgarg2000** [comment]
@pawarspeaks Yes I'm working on this...Busy with the Interview...I'll push code by Tomorrow

**Comment by pawarspeaks** [comment]
sure got it!

**Comment by bhaveshgarg2000** [comment]
@pawarspeaks I'll Push the code by Today.
Sorry for the Delay

**Comment by bhaveshgarg2000** [comment]
Hii @pawarspeaks I have Changed the Structure & JS is working Fine
Please approve this PR
Thanks for giving me a chance to contribute in Open Source
Happy Open Sourcing !!

**Comment by pawarspeaks** [comment]
image
image
@bhaveshgarg2000 could you please make the button size a bit visible and easy to find out also not overlapping to the copyright statement?
Also kindly make it look and work the same across all the pages, do sync the repo to latest commits to get better idea about the improvements😊

**Comment by bhaveshgarg2000** [comment]
image
I have pushed this code
Button isn't Overlapping over Copyright

**Comment by bhaveshgarg2000** [comment]
@pawarspeaks 
You can Checkout this URL [https://deploy-preview-11--devcode-technexus.netlify.app/]

**Comment by pawarspeaks** [comment]
@bhaveshgarg2000 kindly check the contact-us form layout in other pages except the home page.

**Comment by bhaveshgarg2000** [comment]
Sorry for the Inconvenience

**Comment by bhaveshgarg2000** [comment]
@pawarspeaks Hii, Now everything is Updated 
[https://deploy-preview-11--devcode-technexus.netlify.app/]
Happy Open Sourcing !!

**Comment by bhaveshgarg2000** [comment]
Hi @pawarspeaks  I have sorted everything
Please merge my PR

**Comment by pawarspeaks** [comment]
@bhaveshgarg2000 LGTM!! could you please sync your forked repo with the latest changes in the TechNexus and then create a PR?
image
as there are a lot of changes that your forked repo is running behind on, its getting difficult for me to resolve a lot of conflict with the changes in this PR, so it would be great if you do it✨
Thank you!

**Comment by bhaveshgarg2000** [comment]
My Repo is Updated
image

**Comment by pawarspeaks** [comment]
hey @bhaveshgarg2000 I see a lot of conflicts of updates for this PR so I'm closing this one, do open a new Pull Request, sorry for the trouble.
Thank you!
image

**Pull request closed without merging**
