### PR TITLE
Complete UI with New Features & Modern Design

### PR DESCRIPTION
**Pull request by anshulsoni2010**
### Revamped UI & Feature Enhancements 🎨✨
This PR brings a complete UI overhaul, transforming the website into a sleek and modern experience. The design has been significantly updated to improve user experience, ensuring a cleaner, more intuitive interface.

**Key Highlights:**

- Brand-new modern look: A fully revamped, minimalist UI for a fresh and engaging appearance.
- Improved UX flow: Simplified navigation and better user interactions across the site.
- Feature additions: Added several new features alongside the UI improvements to enhance functionality.

Issue: #51 

edit resolves: #51

### CODE REVIEW

**Comment by anshulsoni2010** [comment]
Please share me the logs so that I'll fix it. Because it's getting deployment errors.

**Comment by pawarspeaks** [comment]
@anshulsoni2010 latest logs:
[17:22:36.233] Running build in Washington, D.C., USA (East) – iad1
[17:22:36.352] Cloning github.com/pawarspeaks/TechNexus (Branch: main, Commit: 41ff093)
[17:22:36.991] Cloning completed: 638.249ms
[17:22:37.646] Restored build cache from previous deployment (4XcpMqGbny8NEuvf9dRS7kCBB7Sc)
[17:22:37.728] Running "vercel build"
[17:22:38.144] Vercel CLI 37.8.0
[17:22:38.806] Error while parsing config file: "/vercel/path0/package-lock.json"
[17:22:38.813] Error while parsing config file: "/vercel/path0/package-lock.json"
[17:22:38.817] Error while parsing config file: "/vercel/path0/package-lock.json"
[17:22:38.818] Installing dependencies...
[17:22:53.253] npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[17:22:53.758] npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[17:22:54.019] npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[17:22:54.101] npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
[17:22:54.351] npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[17:22:55.910] npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
[17:23:02.345] 
[17:23:02.346] added 152 packages, removed 81 packages, and changed 30 packages in 23s
[17:23:02.346] 
[17:23:02.346] 144 packages are looking for funding
[17:23:02.346]   run `npm fund` for details
[17:23:02.394] Running "npm run build"
[17:23:02.553] 
[17:23:02.553] > TechNexus@0.1.0 build
[17:23:02.553] > next build
[17:23:02.553] 
[17:23:03.256] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[17:23:03.257] This information is used to shape Next.js' roadmap and prioritize features.
[17:23:03.257] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[17:23:03.257] https://nextjs.org/telemetry
[17:23:03.257] 
[17:23:03.374]   ▲ Next.js 14.2.15
[17:23:03.374] 
[17:23:03.404]    Creating an optimized production build ...
[17:23:26.443]  ✓ Compiled successfully
[17:23:26.444]    Linting and checking validity of types ...
[17:23:29.442] 
[17:23:29.444] Failed to compile.
[17:23:29.448] 
[17:23:29.449] ./app/contributors/page.tsx
[17:23:29.449] 56:25  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[17:23:29.449] 
[17:23:29.449] ./app/offline-events/page.tsx
[17:23:29.449] 145:41  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[17:23:29.449] 
[17:23:29.449] ./app/virtual-events/page.tsx
[17:23:29.449] 142:41  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[17:23:29.449] 
[17:23:29.449] ./components/layout/sections/about.tsx
[17:23:29.450] 106:74  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
[17:23:29.450] 
[17:23:29.450] ./components/layout/sections/community.tsx
[17:23:29.450] 61:29  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[17:23:29.450] 
[17:23:29.450] ./components/layout/sections/footer.tsx
[17:23:29.450] 53:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[17:23:29.450] 98:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[17:23:29.450] 
[17:23:29.450] ./components/layout/sections/hero.tsx
[17:23:29.451] 35:38  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
[17:23:29.451] 47:58  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
[17:23:29.451] 
[17:23:29.451] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[17:23:29.474] Error: Command "npm run build" exited with 1
[17:23:29.997]

**Comment by pawarspeaks** [comment]
@anshulsoni2010 

[20:31:25.421] Running build in Washington, D.C., USA (East) – iad1
[20:31:25.667] Cloning github.com/pawarspeaks/TechNexus (Branch: main, Commit: d1bcb53)
[20:31:26.317] Cloning completed: 649.376ms
[20:31:27.046] Restored build cache from previous deployment (4XcpMqGbny8NEuvf9dRS7kCBB7Sc)
[20:31:27.136] Running "vercel build"
[20:31:27.564] Vercel CLI 37.8.0
[20:31:28.241] Installing dependencies...
[20:31:30.800] npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
[20:31:30.803] npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[20:31:31.662] npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
[20:31:31.760] npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
[20:31:31.783] npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
[20:31:33.880] npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
[20:31:42.377] 
[20:31:42.378] added 158 packages, removed 87 packages, and changed 34 packages in 14s
[20:31:42.378] 
[20:31:42.379] 147 packages are looking for funding
[20:31:42.379]   run `npm fund` for details
[20:31:42.405] Running "npm run build"
[20:31:42.633] 
[20:31:42.633] > technexus@0.1.0 build
[20:31:42.633] > next build
[20:31:42.633] 
[20:31:43.817] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[20:31:43.817] This information is used to shape Next.js' roadmap and prioritize features.
[20:31:43.818] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[20:31:43.818] https://nextjs.org/telemetry
[20:31:43.818] 
[20:31:43.946]   ▲ Next.js 14.2.15
[20:31:43.947] 
[20:31:44.128]    Creating an optimized production build ...
[20:32:04.926]  ✓ Compiled successfully
[20:32:04.927]    Linting and checking validity of types ...
[20:32:07.944] 
[20:32:07.944] Failed to compile.
[20:32:07.944] 
[20:32:07.944] ./app/favourites/page.tsx
[20:32:07.944] 67:41  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
[20:32:07.944] 
[20:32:07.945] ./components/layout/sections/hero.tsx
[20:32:07.945] 35:38  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
[20:32:07.945] 
[20:32:07.945] info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[20:32:07.972] Error: Command "npm run build" exited with 1
[20:32:09.127]

**Comment by pawarspeaks** [comment]
@anshulsoni2010 any updates? we have kept other major issues pending for your UI revamp...please let us know how much time will it take any proposed UI design or images posted here and consistent commits to this issue will help us better manager other relevant issues..expecting an response.
thank you

**Comment by pawarspeaks** [comment]
Didn't receive any response :(
see you around!

**Pull request closed without merging**
