### PR TITLE
capatilized contact and added a online event

### PR DESCRIPTION
**Pull request by aaradhayasingh811**

### CODE REVIEW

**Comment by aaradhayasingh811** [comment]
sir would you please merge my pull request

**Review by pawarspeaks — COMMENTED** [review]
Hey kindly change the date to starting date and use the same date format used in other events
i.e yyyy-mm-dd

**Comment by aaradhayasingh811** [comment]
sir its changed now pls merge my pull request

**Comment by pawarspeaks** [comment]
hey @aaradhayasingh811 do give this repo ⭐ from the top at https://github.com/pawarspeaks/TechNexus

**Pull request merged**
