### PR TITLE
changed heirarchy of file

### LINKED ISSUE #38: more organized files
when I first time saw TechNexus , I saw a lot of mess around and decided to fix it by organising all the files inside the folders.
it gives better readability to the user, by not affecting any piece of code.

## Organized Files
Girl in a jacket

### PR DESCRIPTION
**Pull request by mr-mods-yg**
Closes #38 
better organisation of files

### CODE REVIEW

**Comment by pawarspeaks** [comment]
@mr-mods-yg many event image paths are yet be set, kindly do the needful
image

**Comment by mr-mods-yg** [comment]
ok i am checking it and will fix it

**Comment by mr-mods-yg** [comment]
oh wait a second i think i did something wrong

**Comment by mr-mods-yg** [comment]
My bad. I resolved conflicts by deleting the files. now I fixed it back to normal

**Comment by mr-mods-yg** [comment]
Earlier the link was :
https://technexus-epvy61mtg-pawarspeaks.vercel.app/static/pages/offline-events.html (example)

but I want link to be short so that it looks more clean
after some thinking I decided to leave those files such that the link remains the same:
https://technexus-epvy61mtg-pawarspeaks.vercel.app/offline-events.html (example)

**Pull request merged**
