### PR TITLE
footer enhancement

### PR DESCRIPTION
**Pull request by NiranjanKumar001**
ADDED more option for giving it proper complexity ,added minimalistic animation ,removed the contact page as ,we need it in different page.Also made the footer responsive for all kind of devices.
Screenshot 2024-10-13 041541
Screenshot 2024-10-13 041611
Screenshot 2024-10-13 041626
Screenshot 2024-10-13 041641
Screenshot 2024-10-13 041713
_change you need to add the proper "share" links and proper link for "follow us"_

edit: resolves: #62

### CODE REVIEW

**Comment by pawarspeaks** [comment]
@NiranjanKumar001 this is cool!
could you please remove facebook and reddit..and update all the social links with the ones available on this link: https://dev-code-community.github.io/bio/

**Comment by pawarspeaks** [comment]
> @NiranjanKumar001 this is cool! could you please remove facebook and reddit..and update all the social links with the ones available on this link: https://dev-code-community.github.io/bio/

please update with the correct links!

**Comment by NiranjanKumar001** [comment]
@pawarspeaks i think you have seen the 2nd last deployment of vercel please checkout the lastest deployment ,i copy pasted again so it will show the deployment again for you ,i am attaching the code for confirmation that valid links from dev community site has been added,please recheck !!
Screenshot 2024-10-15 094813
Screenshot 2024-10-15 094837
Screenshot 2024-10-15 094903

**Comment by pawarspeaks** [comment]
@NiranjanKumar001 they are still the wrong links...
please find the correct links at https://dev-code-community.github.io/bio/
for your ease :
https://x.com/_DEVCODE_
https://www.linkedin.com/company/dev-code-community/
https://www.instagram.com/devcode.community/

**Pull request merged**
