### PR TITLE
Create shortedlinklist.py

### PR DESCRIPTION
**Pull request by dakshrajput100**

### CODE REVIEW

**Comment by dakshrajput100** [comment]
shorted Linklist

**Comment by dakshrajput100** [comment]
.

**Comment by pawarspeaks** [comment]
@dakshrajput100 kindly read about the readme file to understand what TechNexus is about and what you are expected to contribute with.
Happy Opensourcing⭐

**Comment by pawarspeaks** [comment]
Not relevant to this repository

**Pull request closed without merging**
