### PR TITLE
[53]Event feature

### LINKED ISSUE #53: Adding event list feature
Screenshot 2024-10-12 171850
Here  adropdown can be added whether the the event is online , offline or hybrid . can you pls assign this issue to me

### PR DESCRIPTION
**Pull request by kshitigambhir**
Adding event list feature (offline/offline)
BEFORE:
Screenshot 2024-10-12 230700
AFTER:
Screenshot 2024-10-12 225831

Enhanced the UI

edit: resolve #53

### CODE REVIEW

**Comment by pawarspeaks** [comment]
Hi @kshitigambhir 
image

please look at the above

**Comment by kshitigambhir** [comment]
@pawarspeaks working on it..

**Comment by kshitigambhir** [comment]
done @pawarspeaks

**Comment by pawarspeaks** [comment]
Hi @kshitigambhir 
please look into the following issue
https://github.com/user-attachments/assets/ad995dd6-e845-4c00-b9dc-52c395ce6bde

image
also please consider sync update and then raise a new pr or update this one itself to help us considering you PR

**Comment by kshitigambhir** [comment]
@pawarspeaks  working on it

**Comment by kshitigambhir** [comment]
done @pawarspeaks

**Comment by kshitigambhir** [comment]
@pawarspeaks can you pls chk I have made changes

**Comment by pawarspeaks** [comment]
https://github.com/user-attachments/assets/2c643f02-6606-4f4b-8e6a-601a92b034bc

@kshitigambhir please check the above video once..and do consider to sync and fork your current forked repo with the latest changes to the main repository (we have major changes to the navbar, you can checkout https://devcode-technexus.vercel.app/ ) 
hope to receive the updated commit in this PR with the new navbar and unchanged serial of the navbar options

**Comment by pawarspeaks** [comment]
https://github.com/user-attachments/assets/5af37b71-9bc6-4d14-9054-63c1e2645260


@kshitigambhir please check the above video once.. and do consider to sync and fork your current forked repo with the latest changes to the main repository (we have major changes to the navbar, you can checkout https://devcode-technexus.vercel.app/ ) 
hope to receive the updated commit in this PR with the new navbar and unchanged serial of the navbar options

**Pull request closed without merging**
