### PR TITLE
Adding Favicon and Title 

### LINKED ISSUE #54: Need to change of favicon and the title
Your site is currently using the default title and favicon. To make it more representative of your project, we should customize both.

Could you please assign this task to update the favicon and set a new title that reflects your site’s purpose?

Screenshot 2024-10-12 174404

### PR DESCRIPTION
**Pull request by Abhi-Jeeet**
Fixed #54 

I have added the title and the favicon and these are the previews , how its look in different devices!!

Screenshot 2024-10-12 225420

Screenshot 2024-10-12 225433

Screenshot 2024-10-12 225447

### CODE REVIEW

**Comment by pawarspeaks** [comment]
Awesome! @Abhi-Jeeet 
Please star the following repo: https://github.com/pawarspeaks/TechNexus
and follow the initiating organization at https://github.com/Dev-Code-Community
to support this project and get your PR merged

**Comment by Abhi-Jeeet** [comment]
> Awesome! @Abhi-Jeeet Please star the following repo: https://github.com/pawarspeaks/TechNexus and follow the initiating organization at https://github.com/Dev-Code-Community to support this project and get your PR merged

Already star your repo.

**Comment by Abhi-Jeeet** [comment]
Already Star your repo and also followed the Dev-Code community.

**Comment by pawarspeaks** [comment]
Sorry for the trouble but you have added a star to https://github.com/Abhi-Jeeet/TechNexus
you need to add to the original repo at https://github.com/pawarspeaks/TechNexus
tag once done!

**Comment by Abhi-Jeeet** [comment]
Ohh sorry, my mistake!!

**Comment by Abhi-Jeeet** [comment]
@pawarspeaks done!!

**Comment by pawarspeaks** [comment]
Thanks!!
Merged!🐿️
Happy Open Sourcing!🚀

**Pull request merged**
