### PR TITLE
added a virtual event

### PR DESCRIPTION
**Pull request by Tusharrgrg**
Hello, sir. I have added a virtual event."
The changes have been tested extensively to ensure that they do not introduce any new issues.
Related Issues: 
#1

### CODE REVIEW

**Comment by Tusharrgrg** [comment]
sir would you please merge my pull request

**Comment by pawarspeaks** [comment]
Hey your forked repo is not synced to the latest version kindly sync to the latest commits and open a pull request

**Comment by pawarspeaks** [comment]
merged @Tusharrgrg do ⭐ the TechNexus repo, thank you!

**Comment by Tusharrgrg** [comment]
@pawarspeaks  sure!

**Pull request merged**
