### PR TITLE
Issue No. #18 [FIXED] Copyright year added in the footer section.

### LINKED ISSUE #18: Copyright year missing in the footer section.
Screenshot 2023-10-14 235116

### PR DESCRIPTION
**Pull request by gauravsingh1281**
Closes #18

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
@pawarspeaks Please assign this pull request to me and add hacktoberfest-accepted label.

**Comment by pawarspeaks** [comment]
could you make the copyright text same on all the pages? @gauravsingh1281

**Comment by gauravsingh1281** [comment]
> could you make the copyright text same on all the pages? @gauravsingh1281

Yes

**Comment by gauravsingh1281** [comment]
Hii @pawarspeaks copyright year added on all the pages with same font size.

**Comment by pawarspeaks** [comment]
@gauravsingh1281 merged, do ⭐ the TechNexus repository, thank you!

**Pull request merged**
