### PR TITLE
Implementation of Contact Page

### PR DESCRIPTION
**Pull request by RakinduM**
Created a separate page for contact us. And removed the contact section, that was in the Footer section and kept a simple footer just to fill the space.
Also added the routing for the contact page.

### CODE REVIEW

**Comment by pawarspeaks** [comment]
Hi @RakinduM 
it looks great but a few things we need to address before mergine..
image


the social media links have been removed kindly add them back to the contact page as well as the footer.
Also add both the logos with their hyperlinks and the social media links to the footer as well.
Another thing is the subject field in contact form...contact form is using an external API that only accepts three fields please keep the form same as earlier.

**Comment by RakinduM** [comment]
@pawarspeaks Sure I'll make those changes. So  is it okay to keep the Footer file as before without changing anything bacause I saw someone working on enhancing Footer. 
And for the social media,  u mean add the social media icons with the relevant links in the Contact page?

**Comment by RakinduM** [comment]
Screenshot 2024-10-13 at 11 21 25
Screenshot 2024-10-13 at 11 16 58


Which one is suits ?

**Comment by pawarspeaks** [comment]
> Screenshot 2024-10-13 at 11 21 25 Screenshot 2024-10-13 at 11 16 58
> Which one is suits ?

second one is better!

**Comment by RakinduM** [comment]
Added the social media icons to Contact page and place the previous footer

**Comment by pawarspeaks** [comment]
Hey @RakinduM !
image
please look into this..your branch deployment page looks to be blank

**Comment by RakinduM** [comment]
> Hey @RakinduM ! image please look into this..your branch deployment page looks to be blank

@pawarspeaks Kindly check it. I guess now it works.

**Comment by pawarspeaks** [comment]
@RakinduM thanks a lot for your contribution!
Happy OpenSourcing!🚀

**Pull request merged**
