### PR TITLE
fix: reset filter issue

### LINKED ISSUE #133: page breaks after resetting filters
**Describe the bug**
Page Breaks when you click on the reset filters at the starting(without adding anything in filter)
**To Reproduce**
1. Go to 'events page'
2. Click on 'Reset Filters'
4. See error (page gets broken doesn't work even I refresh for 3-4 times)

**Screenshots**

https://github.com/user-attachments/assets/b5f58f82-5b4d-4bd0-8501-2a22162f5d39

**Expected behavior**
it should just reload on the same page,something like that without breaking
I've fixed it 

https://github.com/user-attachments/assets/3f9632ba-02aa-4144-92ed-c7500f6d0b83

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I want to work on this under hacktoberfest-accepted tag

### PR DESCRIPTION
**Pull request by vamsi4845**
This PR fixes #133

### CODE REVIEW

**Comment by pawarspeaks** [comment]
hey @richierich0628 its still failing

**Comment by vamsi4845** [comment]
> hey @vamsi4845 its still failing! image

Is url synced with repo check once? and did u merge my code?

**Comment by vamsi4845** [comment]
@pawarspeaks 
image
You didn't merge my code, do that and try again once

**Comment by pawarspeaks** [comment]
@vamsi4845 https://technexus-kqonyg0d6-pawarspeaks-projects.vercel.app/
you can check your recent commit deployment at...
if it passes over there...only then I can merge it

**Comment by vamsi4845** [comment]
> @vamsi4845 https://technexus-kqonyg0d6-pawarspeaks-projects.vercel.app/ You can check your recent commit deployment at... if it passes over there...only then I can merge it

Ok wait,I don't have access to this, and how would you test the issue without merging? I don't understand this and I've just tested it now, working fine for me 

https://github.com/user-attachments/assets/f17e4ef9-df17-4f04-8d85-cb1665951c6a

**Comment by pawarspeaks** [comment]
https://github.com/user-attachments/assets/4616cadd-e7b3-4f45-911d-c889dce5b502

hey @vamsi4845 this is how I can check your code's deployment before merging please check if you've tested it like I'm doing

**Comment by vamsi4845** [comment]
> you can test it locally...

The video I've sent Is from local only

**Pull request merged**
