### PR TITLE
FIX#59

### PR DESCRIPTION
**Pull request by Chhavi9700225780**
Screenshot 2024-10-12 223132

Enhancing the footer design

And

Screenshot 2024-10-12 223112

Create a seprate page for Contact US Page 

IF you like my work Pls merge my Pull request under hacktoberfest
Thanking You !!

### CODE REVIEW

**Comment by pawarspeaks** [comment]
@Chhavi9700225780 

could you check the following 
image
its not having proper spacing when viewing on a different device..please add those commits to this PR and tag me once done

**Comment by Chhavi9700225780** [comment]
@pawarspeaks 


> @Chhavi9700225780
> 
> could you check the following image its not having proper spacing when viewing on a different device..please add those commits to this PR and tag me once done

@pawarspeaks 
I have fix this responsive bug could you pls check this again

I have added gap between the images and headings.
Screenshot 2024-10-13 075528

I have also Fix the position of submit button in mobile view
Screenshot 2024-10-13 075930

**Comment by Chhavi9700225780** [comment]
@pawarspeaks 
I have Added scroll to top button in your website so that user can navigate to top without any cursor movement

Screenshot 2024-10-13 105744

In Mobile View



When we click on this button we navigate to top

**Comment by pawarspeaks** [comment]
@Chhavi9700225780 Thanks for the back-to-top feature and the contact us page!
I've merged this one.
Happy Open Sourcing!🚀

**Pull request merged**
