### PR TITLE
Update offline-events in Amity Noida Google Cloud Study Jams: Communi…

### PR DESCRIPTION
**Pull request by Parth4git**
…ty Meetup

As the Google Cloud Study Jams near its conclusion, we invite all participants to come together and engage in a collaborative session where you can connect with your fellow students

### CODE REVIEW

**Comment by Parth4git** [comment]
@pawarspeaks pls review my pr and merge it

**Comment by Parth4git** [comment]
@pawarspeaks Please review my PR as it is the last week of hackoctoberfest

**Comment by pawarspeaks** [comment]
@Parth4git kindly check the issue with your code!
image
thank you!

**Comment by Parth4git** [comment]
@pawarspeaks I had resolve the problem .Now Please review my pr and merge it

**Comment by pawarspeaks** [comment]
@Parth4git merged. Do ⭐ the TechNexus repository, thank you!

**Pull request merged**
