### PR TITLE
Fixes: #55 [improvment] add modern navbar with animation and scroll effect 

### PR DESCRIPTION
**Pull request by MOHIT-IITP**
Fixes: #55 

https://github.com/user-attachments/assets/59f080a0-10cb-4008-a845-eab98874347d

### CODE REVIEW

**Comment by MOHIT-IITP** [comment]
@pawarspeaks  Please check this

**Comment by MOHIT-IITP** [comment]
@pawarspeaks  please see and merge it

**Comment by MOHIT-IITP** [comment]
@pawarspeaks  bro please merge this , this is going to be my last (4) pr of hactoberfest

**Comment by MOHIT-IITP** [comment]
@pawarspeaks  Please merge this

**Comment by pawarspeaks** [comment]
@MOHIT-IITP thanks for your contribution and patience!
see you around, happy OpenSourcing!🚀

**Pull request merged**
